### ISSUE TITLE
Ruby version requirement

### ISSUE THREAD

**Issue by chihhaohuang** [jwt/ruby-jwe#6]
Hi there,
Installed the gem and got a syntax error.
No ruby version restrictions described on rubygems.org.
Looks like you use keyword arguments which is a feature in Ruby 2.0 and higher.
Could you confirm this?

Uncaught exception: /.../gems/jwe-0.1.1/lib/jwe.rb:22: syntax error, unexpected tLABEL
  def self.encrypt(payload, key, alg: 'RSA-OAEP', enc: 'A128GCM', zip: nil)

Regards

**Comment by aomega08** [comment]
Hi,

Most OpenSSL methods used by this library are only available on >= Ruby 2.0.

Since I was constrained by OpenSSL, I felt safe in using Ruby 2.0+ syntax. I should have mentioned in the .gemspec though.
